export class CategoryUnit {
  id: string = '';

  categoryName: string = '';

  unitOptions: string[] = [];

  defaultUnit: string = '';

  isEnabled: boolean = true;

  sortOrder: number = 0;

  createdAt: string = '';

  updatedAt: string = '';
}

export class CategoryUnitForm {
  categoryName: string = '';

  unitOptions: string[] = [];

  defaultUnit: string = '';

  isEnabled: boolean = true;

  sortOrder: number = 0;
}