export class CustomField {
  id: string = '';

  fieldName: string = '';

  fieldType: string = '';

  enumOptions: string[] = [];

  isEnabled: boolean = true;

  showInList: boolean = false;

  sortOrder: number = 0;

  remark: string = '';

  createdAt: string = '';

  updatedAt: string = '';
}

export class CustomFieldForm {
  fieldName: string = '';

  fieldType: string = '';

  enumOptions: string[] = [];

  isEnabled: boolean = true;

  showInList: boolean = false;

  sortOrder: number = 0;

  remark: string = '';
}