export class RouteConstants {
  static readonly PRODUCT_LIST: string = 'pages/ProductListPage';
  static readonly PRODUCT_CREATE: string = 'pages/ProductCreatePage';
  static readonly PRODUCT_EDIT: string = 'pages/ProductEditPage';
  static readonly PRODUCT_DETAIL: string = 'pages/ProductDetailPage';
  static readonly SETTINGS: string = 'pages/SettingsPage';
  static readonly CATEGORY_UNIT_LIST: string = 'pages/CategoryUnitListPage';
  static readonly CATEGORY_UNIT_EDIT: string = 'pages/CategoryUnitEditPage';
  static readonly CUSTOM_FIELD_LIST: string = 'pages/CustomFieldListPage';
  static readonly CUSTOM_FIELD_EDIT: string = 'pages/CustomFieldEditPage';
}
